### PR TITLE
Disease map

### PR DESCRIPTION
**Pull request by dianakolusheva**
This PR creates new methods in EmmaaModel that allow getting model statements from MINERVA disease maps and custom files.

### CODE REVIEW

**Comment by cthoyt** [comment]
@dianakolusheva I know it's not the exact goal of this PR, but can you imagine adding additional configuration here to allow for the generation of an EMMA model from a GitHub repository holding BEL content where people are also curating it and updating it on a regular basis?

**Comment by dianakolusheva** [comment]
> @dianakolusheva I know it's not the exact goal of this PR, but can you imagine adding additional configuration here to allow for the generation of an EMMA model from a GitHub repository holding BEL content where people are also curating it and updating it on a regular basis?

I imagine so (though probably in a separate PR) if we can say the content is within a scope of a single model (or can be filtered to it). We are using BEL content (large corpus) as tests for most EMMAA models though. Are you talking about a different content? Can it be processed with INDRA PybelProcessor?

**Comment by bgyori** [comment]
I think that's definitely possible and could be really interesting if there is an active curation project around some specific problem.

**Comment by cthoyt** [comment]
I was thinking of this repo: https://github.com/pharmacome/conib. It might be interesting to go back and do a bit more curation there as well. The content is written as BEL files (that are pre-compiled to JSON by the repo itself), so it can be ingested with the PybelProcessor.

I guess WikiPathways could be another kind of repo that is under constant curation that would be interesting too, but that's not specfically related to BEL. I've worked with their SPARQL endpoint and could imagine a couple queries we could use to pull in content to INDRA

**Pull request merged**
