### PR TITLE
Statistic for EMMAA dashboard

### PR DESCRIPTION
**Pull request by dianakolusheva**
This PR generates model and test statistics for EMMAA dashboard. This step will be executed after each test run and it will upload additional JSON file to S3. The following statistics is generated:

- Model Summary: 
-- name
-- number of statements
-- statement types distribution
-- agents distribution
-- statements (hashes) with evidence count
-- English assembled statements mapped to hashes

- Test Summary:
-- number of applied tests
-- number of passed tests
-- ratio of passed tests over total applied
-- English descriptions of tests mapped to hashes
-- hashes of passed tests
-- English descriptions of found paths mapped to test hashes

- Model Delta between two latest rounds:
-- number of statements
-- actual added and removed statements (English)

- Test Delta between two latest round:
-- number of applied tests
-- number of passed tests
-- passed tests ratio
-- added and removed applied tests (English)
-- new passed and new failed tests (English)
-- new paths found and previous paths (for previously passed and now failed tests) (English)

- Changes over time:
-- number of statements
-- number of applied tests
-- number of passed tests
-- ratio of passed tests

Other small changes in this PR are changing the format of model test output to provide better data for statistics and adding a few util functions to access any files on S3 (not only latest).

### CODE REVIEW

**Comment by bgyori** [comment]
This looks great to me! The only substantial issue is that TestRound and StatsGenerator are both untested, I think we should definitely add tests for these classes, is possible, ones that are independent of the changing S3 content.

**Comment by bgyori** [comment]
Actually, looking more closely at the Travis logs, test_run_tests_from_s3 does implicitly use TestRound and StatsGenerator:
```
======================================================================
ERROR: emmaa.tests.test_model_tests.test_run_tests_from_s3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/indralab/emmaa/emmaa/tests/test_model_tests.py", line 23, in test_run_tests_from_s3
    upload_results=False)
  File "/home/travis/build/indralab/emmaa/emmaa/model_tests.py", line 294, in run_model_tests_from_s3
    sg = StatsGenerator(model_name, latest_round=tr)
  File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 268, in __init__
    self.previous_round = self._get_previous_round()
  File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 376, in _get_previous_round
    tr = TestRound.load_from_s3_key(previous_key)
  File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 62, in load_from_s3_key
    test_round = TestRound(json_results)
  File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 51, in __init__
    self.statements = self._get_statements()
  File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 224, in _get_statements
    serialized_stmts = self.json_results[0]['statements']
KeyError: 'statements'
-------------------- >> begin captured logging << --------------------
```

**Comment by dianakolusheva** [comment]
> Actually, looking more closely at the Travis logs, test_run_tests_from_s3 does implicitly use TestRound and StatsGenerator:
> 
> ```
> ======================================================================
> ERROR: emmaa.tests.test_model_tests.test_run_tests_from_s3
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "/home/travis/build/indralab/emmaa/emmaa/tests/test_model_tests.py", line 23, in test_run_tests_from_s3
>     upload_results=False)
>   File "/home/travis/build/indralab/emmaa/emmaa/model_tests.py", line 294, in run_model_tests_from_s3
>     sg = StatsGenerator(model_name, latest_round=tr)
>   File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 268, in __init__
>     self.previous_round = self._get_previous_round()
>   File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 376, in _get_previous_round
>     tr = TestRound.load_from_s3_key(previous_key)
>   File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 62, in load_from_s3_key
>     test_round = TestRound(json_results)
>   File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 51, in __init__
>     self.statements = self._get_statements()
>   File "/home/travis/build/indralab/emmaa/emmaa/analyze_tests_results.py", line 224, in _get_statements
>     serialized_stmts = self.json_results[0]['statements']
> KeyError: 'statements'
> -------------------- >> begin captured logging << --------------------
> ```

This KeyError is due to the fact the previous found test results round has a different structure as we only used a new one for one round. I can also make a separate test independent of S3, but for this one, it will fail until it has two rounds with new structure (will have them today afternoon) or delete older results.

**Comment by bgyori** [comment]
I see, that makes sense@ In any case, I think having unit tests for these classes would be useful so that next time functionalities don't break unexpectedly over time.

**Pull request merged**
