### PR TITLE
Update handling of output from group_and_sort function.

### PR DESCRIPTION
**Pull request by pagreene**
A small update to go along with https://github.com/sorgerlab/indra/pull/1214

### CODE REVIEW

**Comment by pagreene** [comment]
Found some valid test errors, I will have to fix later.

**Comment by pagreene** [comment]
As far as I know, it should be good now. :)

**Comment by dianakolusheva** [comment]
Hi, can you resolve rebase conflicts and update to correct usage of `make_string_from_relation_key` in `model_tests`?

**Comment by pagreene** [comment]
There that ought to work. Hopefully the tests pass. Sorry for the delay!

**Comment by dianakolusheva** [comment]
Thank you! I will fix that one failing test

**Review by dianakolusheva — APPROVED** [review]

**Pull request merged**
